//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string MatricNo { get; set; }
        public int IcNo { get; set; }
        public string Faculty { get; set; }
        public int Year { get; set; }
        public string Course { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Confirmpassword { get; set; }
    }
}
